# -*- coding: utf-8 -*-

import os
import random

import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
from torch.distributions import Categorical

class Generator(nn.Module):
    """Generator """
    def __init__(self, num_emb, batch_size, emb_dim, class_emb_dim, hidden_dim, num_classes, use_cuda,
                 sequence_length, start_token, learning_rate=0.001, reward_gamma=0.95, grad_clip=1.0):
        super(Generator, self).__init__()
        self.num_emb = num_emb
        self.batch_size = batch_size
        self.emb_dim = emb_dim
        self.class_emb_dim = class_emb_dim
        self.pretrain_emb_dim = emb_dim + class_emb_dim
        self.hidden_dim = hidden_dim
        self.use_cuda = use_cuda
        self.sequence_length = sequence_length
        self.start_token = torch.tensor([start_token] * self.batch_size, dtype=torch.long)
        self.learning_rate = learning_rate
        self.reward_gamma = reward_gamma
        self.grad_clip = grad_clip
        self.temperature = 1.0

        self.emb = nn.Embedding(num_emb, emb_dim)
        nn.init.normal_(self.emb.weight, std=0.1)
        self.pretrain_emb = nn.Embedding(num_emb, self.pretrain_emb_dim)
        self.class_emb = nn.Embedding(num_classes, class_emb_dim) # Class embedding

        self.lstm = nn.LSTM(emb_dim + class_emb_dim, hidden_dim, batch_first=True)
        self.lin = nn.Linear(hidden_dim, num_emb)
        self.classifier = nn.Linear(hidden_dim, num_classes)

        self.optimizer = torch.optim.Adam(self.parameters(), lr=learning_rate)

    def init_hidden(self, batch_size):
        h = Variable(torch.zeros((1, batch_size, self.hidden_dim)))
        c = Variable(torch.zeros((1, batch_size, self.hidden_dim)))
        if self.use_cuda:
            h, c = h.cuda(), c.cuda()
        return h, c

    def init_params(self):
        for param in self.parameters():
            param.data.uniform_(-0.05, 0.05)

    def forward(self, x, class_label, hidden):
        """
        Args:
            x: (batch_size, seq_len), sequence of tokens generated by generator
            class_label: (batch_size, ), class label for the sequences
        """
        x = x.to(self.emb.weight.device)
        class_label = class_label.to(self.class_emb.weight.device)
        hidden = tuple(h.to(self.emb.weight.device) for h in hidden)
        emb = self.emb(x) # (batch_size, seq_len, emb_dim)

        # Embedding for class labels and expand to match sequence length
        class_emb = self.class_emb(class_label).unsqueeze(1)  # (batch_size, 1, emb_dim)
        class_emb = class_emb.expand(-1, x.size(1), -1)       # (batch_size, seq_len, emb_dim)
        # Concatenate token embeddings with class embeddings
        combined_emb = torch.cat([emb, class_emb], dim=-1)  # (batch_size, seq_len, emb_dim + class_emb_dim)

        output, hidden = self.lstm(combined_emb, hidden)
        logits = self.lin(output.contiguous().view(-1, self.hidden_dim))
        class_logits = self.classifier(output[:, -1, :])
        return logits.view(x.size(0), x.size(1), -1), class_logits, hidden

    def pretrain_loss(self, x):
        """
        Calculates the pretraining loss.
        x: (batch_size, seq_len)
        logits: (batch_size, seq_len, vocab_size)
        """
        hidden = self.init_hidden(x.size(0))
        x = x.to(self.emb.weight.device)
        hidden = tuple(h.to(self.emb.weight.device) for h in hidden)
        logits, _, _ = self.forward(x, torch.zeros(x.size(0), dtype=torch.long), hidden) # (batch_size, seq_len, vocab_size)
        logits = logits.view(-1, self.num_emb)
        logits = torch.clamp(logits, min=1e-20, max=1.0)
        target = x.view(-1)
        target = F.one_hot(target, num_classes=self.num_emb).float()
        loss = -torch.sum(target * torch.log(logits)) / (self.sequence_length * self.batch_size)
        return loss

    def pretrain_step(self, x):
        """
        Performs a pretraining step on the generator.
        """
        self.optimizer.zero_grad()
        loss = self.pretrain_loss(x)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(self.parameters(), self.grad_clip)
        self.optimizer.step()
        return loss.item()

    def generate(self, class_label):
        """
        Generates a batch of samples along with their class labels.
        """
        hidden = self.init_hidden(self.batch_size)
        x = self.start_token.unsqueeze(1)  # [batch_size, 1]
        if self.use_cuda:
            x = x.cuda()
            hidden = tuple(h.cuda() for h in hidden)

        samples = []
        for _ in range(self.sequence_length):
            logits, _, hidden = self.forward(x, class_label, hidden)
            probs = F.softmax(logits[:, -1, :] / self.temperature, dim=-1)  # [batch_size, num_emb]
            next_token = torch.multinomial(probs, 1).squeeze()  # [batch_size]
            samples.append(next_token)
            x = next_token.unsqueeze(1)

        return torch.stack(samples, dim=1), class_label
